#!/bin/sh

_copyright(){ echo "
  ozh lightweight shell extensions
  2008-2016 - anx @ ulzq de (Sebastian Glaser)
  Licensed under GNU GPL v3"; }
_license(){ echo "
  ozh is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ozh is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this software; see the file COPYING.  If not, write to
  the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
  Boston, MA 02111-1307 USA

  http://www.gnu.org/licenses/gpl.html"; }

cpu(){
  local calcpu='BEGIN{getline;a=$1;b=$2;c=$3;d=$4}{e=($1-a)*100;f=($2-b)*100;g=($3-c)*100;h=($4-d)*100;t=e+f+g+h;printf "%0.0f %0.0f %0.0f %0.0f\n",(e+1)/t*100,(f+1)/t*100,(g+1)/t*100,(h+1)/t*100}'
  local getcpu='(/cpu[^0-9]/){ t=$2+$3+$4+$5;printf "%i %i %i %i\n", $2,$3,$4,$5}'
  [ "@$1" = "@-h" ] && { printf "$bblack$white cpu $R $byellow$black DELAY(0.1) $R sample DELAY seconds of cpu\n"; return 0; }
  ( busybox awk "$getcpu" /proc/stat; sleep 0.1
    busybox awk "$getcpu" /proc/stat; ) | busybox awk "$calcpu"; }

cpubar(){
  [ "@$1" = "@-h" ] && { printf "$bblack$white cpubar $R $byellow$black WIDTH(40) $R show htop-style cpu bar\n"; return 0; }
  cpu | busybox awk '{a="                                        ";
    printf "%s%s%s", "'$byellow'", substr("usr" a,0,sprintf("%0.0f",$1/2.5)), "'$R'"
    printf "%s%s%s", "'$bred'",    substr("sys" a,0,sprintf("%0.0f",$2/2.5)), "'$R'"
    printf "%s%s%s", "'$bblue'",   substr("nic" a,0,sprintf("%0.0f",$3/2.5)), "'$R'"
    printf "%s%s%s", "'$bgreen'",  substr("idl" a,0,sprintf("%0.0f",$4/2.5)), "'$R'"}'; echo; }

ctop(){
  local count=3; [ -n "$1" ] && count="$1"
  [ "@$1" = "@-h" ] && { printf "$bblack$white ctop $R $byellow$black COUNT(3) $R top COUNT cpu-using processes\n"; return 0; }
  Btop -bn1 | busybox awk '
    BEGIN{for(i=0;i<4;i++)getline}
    {$0=substr($0,38,100);c=$1;$1="";
    gsub(/^[ ]*/,"",$0); gsub(/^\{[ ]*/,"",$0); gsub(/^\[[ ]*/,"",$0);
    gsub(/ .*/,"",$0);   gsub(/^.*\//,"",$0);
    gsub(/\]$/,"",$0);   gsub(/\:$/,"",$0);     gsub(/\}$/,"",$0);
    if(c!=""){print c,$0}}' | sort -rn | head -n $count; }

[ -n "$OZH_HELP" ] && _cpu_help(){ cpu -h; cpubar -h; ctop -h; }
true
